#!/bin/bash

echo "🔐 Configuring Langfuse Authentication for Swarm"
echo "================================================"

# Function to get or create API keys
configure_langfuse() {
  echo ""
  echo "📌 Current Langfuse instance: http://localhost:3000"
  echo ""
  echo "To enable traces in Langfuse dashboard:"
  echo ""
  echo "1. Open Langfuse: http://localhost:3000"
  echo "2. Create a project (if not already created)"
  echo "3. Go to Project Settings → API Keys"
  echo "4. Create new API keys (Public + Secret)"
  echo "5. Set environment variables:"
  echo ""
  echo "   export LANGFUSE_PUBLIC_KEY='pk-lf-...'"
  echo "   export LANGFUSE_SECRET_KEY='sk-lf-...'"
  echo ""
  echo "6. Restart swarm agents with authentication:"
  echo "   ./deploy-swarm-agents.sh"
  echo ""
  echo "Alternative: Use Langfuse in development mode"
  echo "============================================"
  echo ""
  echo "For testing without authentication, you can:"
  echo "1. Set LANGFUSE_DEVELOPMENT_MODE=true in Langfuse container"
  echo "2. Or use the local trace files generated by agents"
  echo ""
}

# Check current traces
echo "📊 Current trace generation status:"
echo ""

# Check coordinator traces
if docker exec swarm-coordinator test -f /traces/coordinator.jsonl 2>/dev/null; then
  COORD_TRACES=$(docker exec swarm-coordinator wc -l < /traces/coordinator.jsonl 2>/dev/null || echo "0")
  echo "✅ Coordinator traces: $COORD_TRACES generated"
else
  echo "❌ No coordinator traces found"
fi

# Check builder traces  
if docker exec swarm-tracebuilder test -f /traces/builder.jsonl 2>/dev/null; then
  BUILDER_TRACES=$(docker exec swarm-tracebuilder wc -l < /traces/builder.jsonl 2>/dev/null || echo "0")
  echo "✅ LiveTraceBuilder traces: $BUILDER_TRACES generated"
else
  echo "❌ No builder traces found"
fi

# Check analysis traces
if docker exec swarm-datascout test -f /traces/analysis.jsonl 2>/dev/null; then
  ANALYSIS_TRACES=$(docker exec swarm-datascout wc -l < /traces/analysis.jsonl 2>/dev/null || echo "0")
  echo "✅ DataScout analyses: $ANALYSIS_TRACES completed"
else
  echo "❌ No analysis traces found"
fi

# Check performance metrics
if docker exec swarm-performance test -f /traces/performance.jsonl 2>/dev/null; then
  PERF_TRACES=$(docker exec swarm-performance wc -l < /traces/performance.jsonl 2>/dev/null || echo "0")
  echo "✅ Performance metrics: $PERF_TRACES recorded"
else
  echo "❌ No performance metrics found"
fi

configure_langfuse

echo "📁 View generated traces locally:"
echo "   docker exec swarm-coordinator cat /traces/coordinator.jsonl | jq ."
echo "   docker exec swarm-tracebuilder cat /traces/builder.jsonl | jq ."
echo ""
echo "📊 Monitor live activity:"
echo "   docker logs -f swarm-tracebuilder"
echo "   docker logs -f swarm-coordinator"