FROM node:18-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Copy the entire monorepo
COPY . /monorepo

# Install all dependencies for the monorepo
WORKDIR /monorepo
RUN corepack enable pnpm && pnpm i --no-frozen-lockfile

FROM node:18-alpine AS builder
WORKDIR /app

# Copy monorepo with dependencies
COPY --from=deps /monorepo /monorepo

# Build the dashboard app
WORKDIR /monorepo/apps/dashboard
RUN npm run build

FROM node:18-alpine AS runner
WORKDIR /app

ENV NODE_ENV production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy the built application
COPY --from=builder /monorepo/apps/dashboard/public ./public
COPY --from=builder --chown=nextjs:nodejs /monorepo/apps/dashboard/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /monorepo/apps/dashboard/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000

CMD ["node", "server.js"]